# server:
#     port: 8080

# spring:
#     application:
#         name: API-GATEWAY

# eureka:
#     client:
#         register-with-eureka: true
#         fetch-registry: true
#         serviceUrl:
#             defaultZone: https://evening-caverns-75917.herokuapp.com/eureka
#     # instance:
#     #     hostname: localhost

# ribbon:
#     ReadTimeout: 60000

endpoints:
    restart:
        enabled: true
ribbon:
    ConnectTimeout: 30000
    ReadTimeout: 60000
    maxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
        enabled: true
