server:
    port: 8080

spring:
    application:
        name: API-GATEWAY

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        hostname: localhost
