spring:
    application:
        name: common-service

server:
    port: 8200

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        hostname: localhost
