spring:
    application:
        name: common-service

server:
    port: 9200

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    # instance:
    #     hostname: localhost
