server:
    port: 8301

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: https://geoparking-service-registry.herokuapp.com/eureka
            # Temporary hosting
            # defaultZone: https://parking-service-registry.herokuapp.com/eureka
    instance:
        hostname: geoparking-booking.herokuapp.com
        # Temporary hosting
        # hostname: parking-booking-service.herokuapp.com
        nonSecurePort: 80

spring:
    application:
        name: booking-service

    jpa:
        # database-platform: org.hibernate.dialect.MySQL8Dialect
        # show-sql: true
        hibernate:
            ddl-auto: update
    # datasource:
    #     driver-class-name: com.mysql.cj.jdbc.Driver
    #     url: jdbc:mysql://profile-mysql:3306/geoparking_profile?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
    #     username: sa
    #     password: password
