spring: 
  mvc:
    view:
      prefix: /
      suffix: .html
  jpa:  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
    show-sql: true
    hibernate:  
      ddl-auto: update
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/geo_parking"  
    username: root  
    password: password

    

    

