spring:  
  jpa:  
    show-sql: true
    hibernate:  
      ddl-auto: create-drop  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/geoparking"  
    username: postgres  
    password: root

