server:
    port: 8201

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: https://evening-caverns-75917.herokuapp.com/eureka

    # instance:
    #     hostname: localhost

spring:
    application:
        name: profile-service
    jpa:
        hibernate:
            ddl-auto: update
    # datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:postgresql://localhost:5432/geoparking_profile
    # username: postgres
    # password: password
    # jpa:
    #     database-platform: org.hibernate.dialect.PostgreSQLDialect
    #     # database-platform: org.hibernate.dialect.MySQL8Dialect
    #     show-sql: true
    #     hibernate:
    #         ddl-auto: create-drop
    # properties:
    #     hibernate:
    #         format_sql: true

    # datasource:
    #     driver-class-name: com.mysql.cj.jdbc.Driver
    #     url: jdbc:mysql://profile-mysql:3306/geoparking_profile?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
    #     username: sa
    #     password: password
