spring:
    application:
        name: PARKING-SERVICE
    data:
        mongodb:
            uri: mongodb+srv://geoparking_parking:passwordshouldbestrong@geoparking-parking-serv.8f3zb.mongodb.net/geoparkingDB?retryWrites=true&w=majority
            database: geoparkingDB
server:
    port: 8300

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: https://geoparking-service-registry.herokuapp.com/eureka
    instance:
        hostname: geoparking-parking.herokuapp.com
        nonSecurePort: 80
# passwordshouldbestrong
# geoparking_user

# mongodb+srv://geoparking_parking:<password>@geoparking-parking-serv.8f3zb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
