spring:
    application:
        name: parking-service
    data:
        mongodb:
            database: geoparking
    cache:
        type: redis
        redis:
            cache-null-values: false
            time-to-live: 60000
    redis:
        host: localhost
        port: 6379

server:
    port: 8300

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        hostname: localhost
