spring:
    application:
        name: parking-service
    data:
        mongodb:
            uri: mongodb+srv://geoparking_parking:passwordshouldbestrong@geoparking-parking-serv.8f3zb.mongodb.net/geoparkingDB?retryWrites=true&w=majority
            database: geoparkingDB
    # data:
    #     mongodb:
    #         database: geoparking
    # cache:
    #     type: redis
    #     redis:
    #         cache-null-values: false
    #         time-to-live: 60000
    # redis:
    #     host: localhost
    #     port: 6379

server:
    port: 8300

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    # instance:
    #     hostname: localhost
# logging.level.org.springframework.data.mongodb.repository.Query=DEBUG
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# spring.data.mongodb.database=geoparking
# spring.data.mongodb.host=mongodb://127.0.0.1:27017
# spring.data.mongodb.port=27017
# spring.data.mongodb.authentication-database=[authentication_database]
# spring.data.mongodb.username=[username]
# spring.data.mongodb.password=[password]
